spring.application.name=financial

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/financial
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true

# JWT
jwt.secret=${JWT_SECRET}
